name: Build and Obfuscate BPB Panel
on:
  push:
    branches:
      - main
  schedule:
    # 每天凌晨1:00运行
    - cron: "0 1 * * *"
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          
      - name: 安装混淆工具
        run: |
          npm install -g javascript-obfuscator
          
      - name: 检出 BPB 源码到临时目录
        run: |
          git clone https://github.com/bia-pain-bache/BPB-Worker-Panel.git bpb-source
          
      - name: 构建 BPB worker.js
        run: |
          cd bpb-source
          npm install
          npm run build
          
      - name: 调试：查看构建后的文件结构
        run: |
          echo "=== BPB 源码目录结构 ==="
          ls -la bpb-source/
          echo "=== 查找所有 .js 文件 ==="
          find bpb-source/ -name "*.js" -type f
          echo "=== 查找包含 worker 的文件 ==="
          find bpb-source/ -name "*worker*" -type f
          echo "=== 查找 build 目录 ==="
          find bpb-source/ -name "build" -type d
          if [ -d "bpb-source/build" ]; then
            echo "=== build 目录内容 ==="
            ls -la bpb-source/build/
          fi
          
      - name: 复制构建文件
        run: |
          echo "=== 查找所有 .js 文件并显示大小 ==="
          find bpb-source/ -name "*.js" -type f -exec ls -lh {} \; | grep -E '\.(js)
          
      - name: 清理临时目录
        run: |
          rm -rf bpb-source
          
      - name: 检查文件是否存在
        run: |
          if [ ! -f origin.js ]; then
            echo "错误：origin.js 文件不存在"
            exit 1
          fi
          echo "文件大小: $(wc -c < origin.js) bytes"
          
      - name: 混淆 BPB worker.js
        run: |
          javascript-obfuscator origin.js --output _worker.js \
            --compact true \
            --control-flow-flattening false \
            --dead-code-injection false \
            --identifier-names-generator mangled \
            --rename-globals false \
            --string-array true \
            --string-array-encoding 'rc4' \
            --string-array-threshold 0.75 \
            --transform-object-keys true \
            --unicode-escape-sequence true
            
      - name: 验证混淆结果
        run: |
          if [ ! -f _worker.js ]; then
            echo "错误：混淆失败，_worker.js 文件不存在"
            exit 1
          fi
          echo "混淆后文件大小: $(wc -c < _worker.js) bytes"
          
      - name: 清理中间文件
        run: |
          rm -f origin.js
          
      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: 更新最新的 BPB 面板'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
          
      - name: 查找构建文件并复制 origin.js
        run: |
          echo "=== 专门查找大文件（>50KB） ==="
          FOUND_FILE=""

          # 尝试多个可能的路径
          for path in \
            "bpb-source/build/unobfuscated-worker.js" \
            "bpb-source/dist/unobfuscated-worker.js" \
            "bpb-source/build/worker.js" \
            "bpb-source/dist/worker.js" \
            "bpb-source/_worker.js" \
            "bpb-source/worker.js"
          do
            if [ -f "$path" ]; then
              size=$(stat -c%s "$path" 2>/dev/null || echo "0")
              echo "检查文件 $path，大小：$size bytes"
              if [ "$size" -gt 51200 ]; then
                FOUND_FILE="$path"
                echo "找到大文件：$path (${size} bytes)"
                break
              fi
            fi
          done

          # 如果还没找到，查找所有大于50KB的.js文件
          if [ -z "$FOUND_FILE" ]; then
            echo "在所有目录中查找大于50KB的.js文件："
            LARGE_FILES=$(find bpb-source/ -name "*.js" -type f -size +50k)
            if [ -n "$LARGE_FILES" ]; then
              echo "找到的大文件："
              echo "$LARGE_FILES"
              FOUND_FILE=$(echo "$LARGE_FILES" | head -n1)
              echo "使用第一个大文件：$FOUND_FILE"
            fi
          fi

          # 复制文件
          if [ -n "$FOUND_FILE" ] && [ -f "$FOUND_FILE" ]; then
            cp "$FOUND_FILE" origin.js
            size=$(stat -c%s origin.js 2>/dev/null || echo "0")
            echo "成功复制文件，大小：$size bytes"
          else
            echo "错误：找不到合适大小的构建文件"
            find bpb-source/ -name "*.js" -type f -exec ls -lh {} \;
            exit 1
          fi

          
      - name: 清理临时目录
        run: |
          rm -rf bpb-source
          
      - name: 检查文件是否存在
        run: |
          if [ ! -f origin.js ]; then
            echo "错误：origin.js 文件不存在"
            exit 1
          fi
          echo "文件大小: $(wc -c < origin.js) bytes"
          
      - name: 混淆 BPB worker.js
        run: |
          javascript-obfuscator origin.js --output _worker.js \
            --compact true \
            --control-flow-flattening false \
            --dead-code-injection false \
            --identifier-names-generator mangled \
            --rename-globals false \
            --string-array true \
            --string-array-encoding 'rc4' \
            --string-array-threshold 0.75 \
            --transform-object-keys true \
            --unicode-escape-sequence true
            
      - name: 验证混淆结果
        run: |
          if [ ! -f _worker.js ]; then
            echo "错误：混淆失败，_worker.js 文件不存在"
            exit 1
          fi
          echo "混淆后文件大小: $(wc -c < _worker.js) bytes"
          
      - name: 清理中间文件
        run: |
          rm -f origin.js
          
      - name: 提交更改
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: 更新最新的 BPB 面板'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
          push_options: '--set-upstream'
