name: Obfuscate Local BPB Worker

on:
  push:
    branches:
      - main
  schedule:
    # 每天凌晨1:00运行
    - cron: "0 1 * * *"

permissions:
  contents: write

jobs:
  obfuscate:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: 安装混淆器
        run: npm install -g javascript-obfuscator

      - name: 确认本地 worker 文件
        id: check_worker
        run: |
          WORKER_FILE="./dist/worker.js"
          if [ ! -f "$WORKER_FILE" ]; then
            echo "❌ 未找到 $WORKER_FILE，请先构建 worker.js"
            exit 1
          fi
          echo "worker_file=$WORKER_FILE" >> $GITHUB_OUTPUT

      - name: 混淆本地 worker.js (专属逻辑)
        run: |
          javascript-obfuscator "${{ steps.check_worker.outputs.worker_file }}" --output _worker.js \
            --compact true \
            --control-flow-flattening true \
            --dead-code-injection true \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array true \
            --string-array-encoding rc4 \
            --string-array-threshold 0.9 \
            --transform-object-keys true \
            --unicode-escape-sequence true \
            --split-strings true \
            --split-strings-chunk-length 5

      - name: 提交混淆后的文件
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ":arrow_up: 更新专属混淆后的 BPB worker"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          push_options: "--set-upstream"
